version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: ${PMA_HOST}
      UPLOAD_MAX_FILESIZE: 10M
      POST_MAX_SIZE: 10M
      MAX_INPUT_TIME: 300
      MAX_EXECUTION_TIME: 300
    ports:
      - 80
    networks:
      - dokploy-network
    restart: always

networks:
  dokploy-network:
    external: true
