version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - 80
    networks:
      - dokploy-network
    restart: always

networks:
  dokploy-network:
    external: true
