version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: ${PMA_HOST}
    ports:
      - 80
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - dokploy-network
    restart: always

networks:
  dokploy-network:
    external: true
