version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_CHARSET: ${WORDPRESS_DB_CHARSET}
      WORDPRESS_DB_COLLATE: ${WORDPRESS_DB_COLLATE}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: ${WORDPRESS_CONFIG_EXTRA}
    volumes:
      - wp-data:/var/www/html
    ports:
      - 80
    networks:
      - dokploy-network
    restart: always

volumes:
  wp-data:

networks:
  dokploy-network:
    external: true