version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - socialhearts-test-37n2mo_wp-data:/var/www/html
    ports:
      - 80
    networks:
      - dokploy-network
    restart: always

volumes:
  socialhearts-test-37n2mo_wp-data:

networks:
  dokploy-network:
    external: true